### ISSUE TITLE
Make static variables avialable via `observable` mechanism

### ISSUE THREAD

**Issue by hexaeder** [JuliaDynamics/NetworkDynamics.jl#112]
I've used [this code](https://github.com/hexaeder/BlockSystems.jl/blob/4209cf12ed18a4274dbd44ac0019f33fabdb4d3a/src/function_generation.jl#L151-L165) in BlockSystems to allow acces to `sol[:removed_variables]`. We can probably do this in NetworkDynamics in a simliar way for the static edge variables.

**Comment by acejolanda** [comment]
I have tried to implement the observed mechanism in the `NetworkDynamics` module. However, the symbols for the edges in the `collect_ve_info` function would still need to be modified so that the edge symbols differ which would allow explicit access to the respective edge variables in the solution object. A possible syntax for a two dimensional edge connecting vertex 1 and 2 could be:
`[e_1_2_1, e_1_2_2, e_1_2_1_inv, e_1_2_2_inv]`
where the first two integers indicate the source and destination vertex. The third integer indicates the dimension of the edge variable and the term `inv` specifies the internal inverse edge variable.

**Comment by lindnemi** [comment]
https://github.com/PIK-ICoNe/NetworkDynamics.jl/tree/acccessing_edge_variables

**Comment by hexaeder** [comment]
implemented in #140
